language: python

python:
  - "3.4"

sudo: false

before_install:
  - pip install flake8
  - pip install coveralls
  - pip install matplotlib
  - pip install prettyplotlib
  - pip install elasticsearch-dsl
  - pip install grimoire-elk

# install:
#   - ./setup.py install

script:
  - flake8 .
#  - cd tests && ./run_tests.py
