language: python

python:
  - "3.4"

sudo: false

services:
  - elasticsearch

# sleep to wait for Elasticsearch init
before_install:
  - sleep 10
  - pip install -r "requirements.txt"
  - pip install flake8
  - pip install coveralls

# install:
#   - ./setup.py install

script:
  - flake8 .
  - cd tests
  - coverage run run_tests.py

after_success:
  - coveralls
